services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "../"
        target: "/workspace"
        consistency: cached
    command: sleep infinity
